### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET localhost:8081

###
GET localhost:8081/test


###
GET http://localhost:8081/content/sample.html


###

GET http://localhost:8081/error


###

GET http://localhost:8081/tasks


### Low, Medium, High, Vital

GET localhost:8081/tasks/byPriority/Vital

###

GET localhost:8081/task-ui/task-form.html

